// Language management utility
export type Language = 'en' | 'ta';

const translations: Record<Language, Record<string, string>> = {
  en: {
    'header.findRoom': 'Find a Room',
    'header.listRoom': 'List a Room',
    'header.roommateGroups': 'Roommate Groups',
    'header.dashboard': 'Dashboard',
    'header.logout': 'Logout',
    'header.login': 'Login',
    'header.signup': 'Sign Up',
    'header.profile': 'Profile',
    'findRoom.title': 'Find Your Perfect Room',
    'findRoom.subtitle': 'Search and filter rooms based on your preferences',
    'findRoom.searchPreferences': 'Search Preferences',
    'findRoom.location': 'Preferred Location',
    'findRoom.minBudget': 'Min Budget ($)',
    'findRoom.maxBudget': 'Max Budget ($)',
    'findRoom.paymentType': 'Payment Type',
    'findRoom.roomType': 'Room Type',
    'findRoom.capacity': 'Number of Roommates',
    'findRoom.studentFriendly': 'Student/Working',
    'findRoom.smoking': 'Smoking Preference',
    'findRoom.food': 'Food Preference',
    'findRoom.social': 'Social Preference',
    'findRoom.gender': 'Gender Preference',
    'findRoom.resetFilters': 'Reset Filters',
    'findRoom.availableRooms': 'Available Rooms',
    'findRoom.noRooms': 'No rooms found matching your preferences. Try adjusting your filters.',
    'findRoom.contactOwner': 'Contact Owner',
    'gender.male': 'Male',
    'gender.female': 'Female',
    'gender.any': 'Any',
    'listRoom.title': 'List Your Room',
    'listRoom.subtitle': 'Fill in the details to list your available room',
    'listRoom.location': 'Location',
    'listRoom.roomType': 'Room Type',
    'listRoom.capacity': 'Capacity',
    'listRoom.monthlyRent': 'Monthly Rent ($)',
    'listRoom.availabilityDate': 'Availability Date',
    'listRoom.leaseOption': 'Lease Option',
    'listRoom.description': 'Description',
    'listRoom.roomOccupancy': 'Room Occupancy',
    'listRoom.occupancyType': 'Room Occupancy Type',
    'listRoom.currentMembers': 'Current Members Present',
    'listRoom.availableSlots': 'Available Slots',
    'listRoom.existingMembersPreferences': 'Existing Members\' Preferences (lifestyle tags)',
    'listRoom.ownerContactInformation': 'Owner Contact Information',
    'listRoom.ownerName': 'Your Name',
    'listRoom.ownerPhone': 'Phone Number',
    'listRoom.ownerEmail': 'Email Address',
    'listRoom.roomPhotos': 'Room Photos',
    'listRoom.addPhotos': 'Add up to 5 room photos using image URLs or upload from your device',
    'listRoom.pasteImageUrl': 'Paste image URL here',
    'listRoom.addPhoto': 'Add Photo',
    'listRoom.uploadFromDevice': 'Upload from Device',
    'listRoom.photosAdded': 'photos added',
    'listRoom.verification': 'Verification (Optional)',
    'listRoom.verificationNote': 'Add verification details to build trust with potential renters. You can update these later from your dashboard.',
    'listRoom.preferences': 'Preferences',
    'listRoom.studentFriendly': 'Student Friendly',
    'listRoom.smokingAllowed': 'Smoking Allowed',
    'listRoom.foodPreference': 'Food Preference',
    'listRoom.socialPreference': 'Social Preference',
    'listRoom.submitListing': 'Submit Listing',
    'listRoom.cancel': 'Cancel',
    'listRoom.yes': 'Yes',
    'listRoom.no': 'No',
    'listRoom.private': 'Private',
    'listRoom.shared': 'Shared',
    'listRoom.fullyVacant': 'Fully Vacant',
    'listRoom.partiallyOccupied': 'Partially Occupied (Sharing Available)',
    'listRoom.leaseOnly': 'Lease only',
    'listRoom.rentOnly': 'Rent only',
    'listRoom.rentPlusLease': 'Rent + Lease',
    'listRoom.leaseAmount': 'Lease Amount ($)',
    'listRoom.vegetarian': 'Vegetarian',
    'listRoom.nonVegetarian': 'Non-Vegetarian',
    'listRoom.vegan': 'Vegan',
    'listRoom.quiet': 'Quiet',
    'listRoom.social': 'Social',
  },
  ta: {
    'header.findRoom': 'அறை தேடுங்கள்',
    'header.listRoom': 'அறையை பட்டியலிடுங்கள்',
    'header.roommateGroups': 'சக வாসி குழுக்கள்',
    'header.dashboard': 'டாஷ்போர்ட்',
    'header.logout': 'வெளியேறு',
    'header.login': 'உள்நுழைக',
    'header.signup': 'பதிவு செய்யவும்',
    'header.profile': 'சுயவிவரம்',
    'findRoom.title': 'உங்கள் சரியான அறையைக் கண்டுபிடிக்கவும்',
    'findRoom.subtitle': 'உங்கள் விருப்பங்களின் அடிப்படையில் அறைகளைத் தேடி வடிகட்டுங்கள்',
    'findRoom.searchPreferences': 'தேடல் விருப்பங்கள்',
    'findRoom.location': 'விரும்பிய இடம்',
    'findRoom.minBudget': 'குறைந்தபட்ச பட்ജெட் ($)',
    'findRoom.maxBudget': 'அதிகபட்ச பட்ജெட் ($)',
    'findRoom.paymentType': 'பணம் செலுத்தும் வகை',
    'findRoom.roomType': 'அறையின் வகை',
    'findRoom.capacity': 'சக வாசிகளின் எண்ணிக்கை',
    'findRoom.studentFriendly': 'மாணவர்/தொழிலாளி',
    'findRoom.smoking': 'புகைபிடிக்கும் விருப்பம்',
    'findRoom.food': 'உணவு விருப்பம்',
    'findRoom.social': 'சामाजிக விருப்பம்',
    'findRoom.gender': 'பாலினம் விருப்பம்',
    'findRoom.resetFilters': 'வடிப்பிகளை மீட்டமை',
    'findRoom.availableRooms': 'கிடைக்கக்கூடிய அறைகள்',
    'findRoom.noRooms': 'உங்கள் விருப்பங்களுடன் பொருந்தக்கூடிய அறைகள் எதுவும் கிடைக்கவில்லை. உங்கள் வடிப்பிகளை சரிசெய்ய முயற்சி செய்யவும்.',
    'findRoom.contactOwner': 'உரிமையாளரைத் தொடர்பு கொள்ளவும்',
    'gender.male': 'ஆண்',
    'gender.female': 'பெண்',
    'gender.any': 'எதுவும்',
    'listRoom.title': 'உங்கள் அறையை பட்டியலிடுங்கள்',
    'listRoom.subtitle': 'உங்கள் கிடைக்கக்கூடிய அறையை பட்டியலிட விவரங்களை நிரப்பவும்',
    'listRoom.location': 'இடம்',
    'listRoom.roomType': 'அறையின் வகை',
    'listRoom.capacity': 'திறன்',
    'listRoom.monthlyRent': 'மாதாந்திர வாடகை ($)',
    'listRoom.availabilityDate': 'கிடைக்கக்கூடிய தேதி',
    'listRoom.leaseOption': 'குத்தகை விருப்பம்',
    'listRoom.description': 'விளக்கம்',
    'listRoom.roomOccupancy': 'அறை ஆக்கிரமிப்பு',
    'listRoom.occupancyType': 'அறை ஆக்கிரமிப்பு வகை',
    'listRoom.currentMembers': 'தற்போதைய உறுப்பினர்கள்',
    'listRoom.availableSlots': 'கிடைக்கக்கூடிய இடங்கள்',
    'listRoom.existingMembersPreferences': 'தற்போதைய உறுப்பினர்களின் விருப்பங்கள் (வாழ்க்கை முறை குறிச்சொற்கள்)',
    'listRoom.ownerContactInformation': 'உரிமையாளர் தொடர்பு தகவல்',
    'listRoom.ownerName': 'உங்கள் பெயர்',
    'listRoom.ownerPhone': 'தொலைபேசி எண்',
    'listRoom.ownerEmail': 'மின்னஞ்சல் முகவரி',
    'listRoom.roomPhotos': 'அறை புகைப்படங்கள்',
    'listRoom.addPhotos': 'பட URL களைப் பயன்படுத்தி அல்லது உங்கள் சாதனத்திலிருந்து பதிவேற்றுவதன் மூலம் 5 வரை அறை புகைப்படங்களைச் சேர்க்கவும்',
    'listRoom.pasteImageUrl': 'பட URL ஐ இங்கே ஒட்டவும்',
    'listRoom.addPhoto': 'புகைப்படத்தைச் சேர்க்கவும்',
    'listRoom.uploadFromDevice': 'சாதனத்திலிருந்து பதிவேற்றவும்',
    'listRoom.photosAdded': 'புகைப்படங்கள் சேர்க்கப்பட்டுள்ளன',
    'listRoom.verification': 'சரிபார்ப்பு (விரும்பினால்)',
    'listRoom.verificationNote': 'சரிபார்ப்பு விவரங்களைச் சேர்த்து சாத்தியமான வாடகையாளர்களுடன் நம்பிக்கை உருவாக்கவும். நீங்கள் உங்கள் டாஷ்போர்டிலிருந்து இவற்றை பின்னர் புதுப்பிக்கலாம்.',
    'listRoom.preferences': 'விருப்பங்கள்',
    'listRoom.studentFriendly': 'மாணவர் நட்பு',
    'listRoom.smokingAllowed': 'புகைபிடிப்பு அனுமதிக்கப்பட்டுள்ளது',
    'listRoom.foodPreference': 'உணவு விருப்பம்',
    'listRoom.socialPreference': 'சामாजிக விருப்பம்',
    'listRoom.submitListing': 'பட்டியலை சமர்ப்பிக்கவும்',
    'listRoom.cancel': 'ரத்துசெய்யவும்',
    'listRoom.yes': 'ஆம்',
    'listRoom.no': 'இல்லை',
    'listRoom.private': 'தனிப்பட்ட',
    'listRoom.shared': 'பகிரப்பட்ட',
    'listRoom.fullyVacant': 'முழுவதுமாக வெற்று',
    'listRoom.partiallyOccupied': 'பகுதியளவு ஆக்கிரமிக்கப்பட்டுள்ளது (பகிர்வு கிடைக்கிறது)',
    'listRoom.leaseOnly': 'குத்தகை மட்டுமே',
    'listRoom.rentOnly': 'வாடகை மட்டுமே',
    'listRoom.rentPlusLease': 'வாடகை + குத்தகை',
    'listRoom.leaseAmount': 'குத்தகை தொகை ($)',
    'listRoom.vegetarian': 'சைவ',
    'listRoom.nonVegetarian': 'அசைவ',
    'listRoom.vegan': 'சுத்த சைவ',
    'listRoom.quiet': 'அமைதியான',
    'listRoom.social': 'சামாजிக',
  },
};

export const getLanguage = (): Language => {
  const stored = localStorage.getItem('language');
  if (stored === 'en' || stored === 'ta') {
    return stored;
  }
  return 'en';
};

export const setLanguage = (language: Language) => {
  localStorage.setItem('language', language);
  // Dispatch custom event for other components to listen
  window.dispatchEvent(new Event('languagechange'));
};

export const t = (key: string, language?: Language): string => {
  const lang = language || getLanguage();
  return translations[lang]?.[key] || key;
};

export const toggleLanguage = (): Language => {
  const current = getLanguage();
  const next = current === 'en' ? 'ta' : 'en';
  setLanguage(next);
  return next;
};
